name: Test Local Runner

on: [push]

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]

    defaults:
      run:
        shell: powershell   # ensures it runs on your Windows PowerShell

    steps:
      - name: Print message
        run: |
          Write-Host "🎉 Hello from my local Windows runner!"
          Get-Date
