name: Minimal Test

on: [push]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
      - name: Build test image
        run: docker build . -t test:latest
      - name: List images
        run: docker images
